### PR TITLE
RE-90: Accessibility improvements for route links

### PR DESCRIPTION
**Pull request by CR96**
#### Description
Add `aria-label` attributes to `Stops` and `Schedule` link icons for screen reader users.

### CODE REVIEW

**Comment by maxatdetroit** [comment]
Hi again @CR96, and thanks again for working on this! Sorry for the late response.

I can help get this merged in if you're still interested in working on it. Let me know in the next couple weeks.

**Comment by CR96** [comment]
Hi @maxatdetroit, I'm still interested! I'll rebase this PR for you shortly. I'm also going to check the latest WCAG guidelines to see if this change is still necessary.

**Comment by maxatdetroit** [comment]
@CR96 , looks like the links on 'schedule' and 'stops' links/buttons may have sufficient context without the aria labels. That being said, I don't have a screen reader set up locally so can't say for sure what the experience is like.

image

image

What do you think? Are the aria labels necessary?

**Comment by CR96** [comment]
Agreed, same rationale as #89. The context is sufficient.

You might see new PRs from co-collaborators shortly that address more targeted a11y issues, but these two can be closed. Thanks for the review!

**Pull request closed without merging**
