### PR TITLE
RE-88: Accessibility improvements for top navigation

### PR DESCRIPTION
**Pull request by CR96**
#### Description
Add `aria-label` attributes to navigation links for screen reader users.
Also add `aria-label` attribute to "DDOT" navigation link for proper pronunciation.

This closes issue #88.

### CODE REVIEW

**Comment by maxatdetroit** [comment]
Hey @CR96, thanks for working on this! Sorry for the late response.

I can help get this merged in if you're still interested in working on it. Let me know in the next couple weeks.

**Comment by CR96** [comment]
Hi @maxatdetroit, I'm still interested! I'll rebase this PR for you shortly. I'm also going to check the latest WCAG guidelines to see if this change is still necessary.

**Comment by maxatdetroit** [comment]
@CR96 WCAG guideline are [pretty loose on links](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html). Looks like the current build of the site has sufficient text to describe the 'home' and 'about this site' links, so I'm not sure if those labels are absolutely necessary (but couldn't hurt). Adding in the phonetic `d dot' is a great idea. 

Home button A11Y:
image

About this site A11Y:
image

**Comment by CR96** [comment]
Disregard commit 02f519f from just now, I rolled that back. PR should be even with main now

**Comment by CR96** [comment]
I agree on the labels being unnecessary. Also, reading some more recent articles on screen reader pronunciation and speaking with someone who works in that space, it appears forcing pronunciation is actually bad practice:

https://adrianroselli.com/2023/04/dont-override-screen-reader-pronunciation.html

In light of that, I think you can close this PR. Thanks for reviewing it!

**Comment by maxatdetroit** [comment]
Thanks for following up 💯

**Pull request closed without merging**
